// Карта маршрутов mhtest.ru, полученная из https://mhtest.ru/sitemap.xml.
// Используется тестом mhtest-ru-routes.spec.js для проверки, что все страницы открываются.

export const BASE_URL = 'https://mhtest.ru';

export const ROUTES = [
    '/',
    // '/eco-smart', // заведомо битый: 404
    // '/go-plus', // заведомо битый: 404
    '/it-accreditation',
    '/podbor-oborudovaniya',
    '/sovmestimost-kotlov',
    '/products/',
    '/products/new/',
    '/products/controllers/',
    '/products/controllers/myheat-go',
    '/products/controllers/myheat-go-plus',
    '/products/controllers/myheat-smart-2',
    '/products/controllers/myheat-pro',
    '/products/controllers/myheat-eco-smart',
    '/products/expansion-units/',
    '/products/expansion-units/rl2',
    '/products/expansion-units/rl2s',
    '/products/expansion-units/rl6',
    '/products/expansion-units/rl6s',
    '/products/expansion-units/rdt',
    '/products/expansion-units/digital-bus-adapter',
    '/products/expansion-units/bl-myheat-eco',
    '/products/expansion-units/myheat-di6',
    '/products/expansion-units/blok-rasshireniya-diskretno-analogovyix-vxodov/vyixodov-myheat-io4',
    '/products/expansion-units/myheat-ups',
    '/products/expansion-units/myheat-ntc-1wire',
    '/products/expansion-units/myheat-rl6w',
    '/products/expansion-units/myheat-rl6sw',
    '/products/expansion-units/adapter-rinnai',
    '/products/sensors/',
    '/products/sensors/termostat-myheat',
    '/products/sensors/termostat-myheat-white',
    '/products/sensors/termostat-myheat-silver',
    '/products/sensors/datchik-wirelesssensor',
    '/products/sensors/radiodatchik-temperaturyi-ulichnyij',
    '/products/sensors/datchik-wiredsensor',
    '/products/sensors/datchik-temperaturyi-myheat-provodnoj-komnatnyij-nk',
    '/products/sensors/datchik-temperaturyi-myheat-ntc-provodnoj-komnatnyij',
    '/products/sensors/datchik-temperaturyi-v-kolbe-myheat-ntc-10k',
    '/products/sensors/datchik-flasksensor',
    '/products/sensors/datchik-flasksensor-3-m',
    '/products/aksessuaryi/',
    '/products/aksessuaryi/datchik-davleniya-4-20ma',
    '/products/aksessuaryi/perehodnik-mhu02',
    '/products/aksessuaryi/datchik-protechki-neptun-sw-005-5m',
    '/products/aksessuaryi/blok-pitaniya-faraday',
    '/docs/',
    '/docs/getting-started/obzor-novogo-interfejsa-lichnogo-kabineta-myheat',
    '/docs/connection/',
    '/docs/connection/sxemyi-podklyucheniya-myheat-gsm',
    // '/docs/connection/sxemyi-podklyucheniya-myheat-smart', // заведомо битый: ERR_CONNECTION_TIMED_OUT
    '/docs/connection/sxemyi-podklyucheniya-myheat-smart-2',
    '/docs/connection/sxemyi-podklyucheniya-my-heat-pro',
    '/docs/other/',
    '/docs/other/alisa-golosovoj-pomoshhnik',
    '/docs/other/avtomatizatsiya-raboty-sistemy-teplykh-polov',
    '/docs/other/upravleniye-sredami',
    '/docs/other/sovmestimoe-oborudovanie',
    '/docs/other/sczenarii',
    '/obucheniye-montazhnikov',
    '/sezon-podarkov-ot-myheat',
    '/o-kompanii',
    '/kontaktyi',
    '/findengineer',
    '/sellers',
    '/payment',
    '/eco-smart-page',
];
